// src/shared/errors/errorCodes.js
export const ERROR_CODES = {
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  INVALID_OAUTH_PROVIDER: "INVALID_OAUTH_PROVIDER",

  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",

  INTERNAL_SERVICE_ERROR: "INTERNAL_SERVICE_ERROR",
};
