// src/shared/errors/errorCodes.ts

export enum ERROR_CODES {
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  INVALID_OAUTH_PROVIDER = "INVALID_OAUTH_PROVIDER",
  VALIDATION_FAILED = "VALIDATION_FAILED",
  INVALID_OAUTH_TOKEN = "INVALID_OAUTH_TOKEN",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",

  INTERNAL_SERVICE_ERROR = "INTERNAL_SERVICE_ERROR",
} 