schema
  @link(
    url: "https://specs.apollo.dev/federation/v2.11"
    import: ["@key","@external","@shareable"]
  ) {
  query: Query
  mutation: Mutation
}

scalar DateTime

directive @auth(requires: [Role!] = []) on FIELD_DEFINITION | OBJECT
directive @public on FIELD_DEFINITION

# =====================
# User (REFERENCE ONLY)
# =====================
extend type User @key(fields: "id") {
  id: ID! @external
}

enum Role {
  ADMIN
  AGENT
  OWNER
  CUSTOMER
}

# =====================
# Auth-only Role
# (used ONLY for authorization, NOT user data)
# =====================


# =====================
# OAuth Provider
# =====================
enum OAuthProvider {
  GOOGLE
  FACEBOOK
  GITHUB
  APPLE
  
}

# =====================
# Query
# =====================
type Query {
  me: User @shareable
  user(id: ID!): User @shareable
  mySessions: [Session!]!
  OnlineSessions: [Session!]!
}

type Session {
  id: ID!
  deviceId: String
  userAgent: String
  ip: String
  lastSeenAt: DateTime
}
# =====================
# Mutation
# =====================
type Mutation {
  oauthLogin(
    provider: OAuthProvider!
    idToken: String!
  ): AuthPayload! @public

  refreshToken(refreshToken: String!): AuthTokens!


  logout: Boolean!
  revokeToken: Boolean!

  bindOAuth(
    provider: OAuthProvider!
    idToken: String!
  ): User! @auth

  unbindOAuth(
    provider: OAuthProvider!
  ): User! @auth

  revokeSession(sessionId: String!): Boolean!
}


# =====================
# Payloads
# =====================
type AuthPayload {
  user: User!
  accessToken: String!
  refreshToken: String!
}

type AuthTokens {
  accessToken: String!  
}

# =====================
# Admin / Audit Types
# =====================
type AdminMergeResult {
  success: Boolean!
  mergedFrom: ID!
  mergedInto: ID!
}

type RiskEvent {
  userId: ID!
  type: String
  provider: OAuthProvider
  ip: String
  userAgent: String
  createdAt: DateTime
  deviceId: String
}

type AdminMergePreview {
  fromUser: MergeUserSnapshot!
  toUser: MergeUserSnapshot!

  credentialsToMove: [CredentialPreview!]!
  refreshTokensToMove: Int!

  warnings: [String!]!
  mergeAllowed: Boolean!
}

# ⚠️ These are SNAPSHOTS, not User
type MergeUserSnapshot {
  userId: ID!
  email: String
  role: Role! 
  createdAt: DateTime
  credentialCount: Int!
  providers: [OAuthProvider!]!
}

type CredentialPreview {
  id: ID!
  provider: OAuthProvider!
  email: String
  lastLoginAt: DateTime
}
