# user.schema.graphql

schema
  @link(url: "https://specs.apollo.dev/federation/v2.11", import: ["@key", "@shareable","@external"]) {
  query: Query
  mutation: Mutation
}

scalar DateTime
type User {
  id: ID!
  email: String
  role: UserRole!
  profile: UserProfile
  status: UserStatus!
  createdAt: DateTime!
}

type UserProfile {
  name: String
  avatar: String
}

enum UserRole {
  USER
  ADMIN
}

enum UserStatus {
  ACTIVE
  DEACTIVATED
}

"""
⚠️ 只允许被 Auth 子图调用
"""
type Query {
  userByEmail(email: String!): User
  userById(id: ID!): User
}

"""
⚠️ OAuth 专用写入口
"""
type Mutation {
  createOAuthUser(input: CreateOAuthUserInput!): User!
  deactivateUser(userId: ID!): Boolean!
}

input CreateOAuthUserInput {
  email: String!
  profile: UserProfileInput
  provider: OAuthProvider!
}

input UserProfileInput {
  name: String
  avatar: String
}

enum OAuthProvider {
  GOOGLE
  GITHUB
  FACEBOOK
  LINE
  APPLE
}
