schema
  @link(
    url: "https://specs.apollo.dev/federation/v2.11"
    import: ["@key", "@shareable"]
  
  ) {
  query: Query
  mutation: Mutation
}

scalar DateTime

"""
User subgraph 是 User 的唯一 owner
"""
type User @key(fields: "id") {
  id: ID!
  email: String! @shareable
  role: Role! @shareable
  profile: Profile
  status: UserStatus!
  createdAt: DateTime!
}

type Profile {
  name: String
  avatar: String
}

enum Role {
  ADMIN
  AGENT
  OWNER
  CUSTOMER
  PENDING_AGENT
}

enum UserStatus {
  ACTIVE
  DEACTIVATED
}

type Query {
  userByEmail(email: String!): User
  userById(id: ID!): User
}

type Mutation {
  createOAuthUser(input: CreateOAuthUserInput!): User!
  deactivateUser(userId: ID!): Boolean!
}

input CreateOAuthUserInput {
  email: String!
  profile: ProfileInput
}

input ProfileInput {
  name: String
  avatar: String
}