schema @link(url: "https://specs.apollo.dev/federation/v2.11", import: ["@key","@external"]) {
  query: Query
  mutation: Mutation
}

scalar DateTime
directive @auth(
  requires: [Role!] = []
) on FIELD_DEFINITION | OBJECT
directive @public on FIELD_DEFINITION
directive @requiresRole(
  role: Role!
) on FIELD_DEFINITION

type Query {
  properties: [Property]
}

type Mutation {
  createProperty(title: String!, price: Int!): Property
   @auth(requires: [AGENT, ADMIN])
   deleteProperty(id: ID!): Boolean @requiresRole(role: ADMIN)
}

type Property @key(fields: "id") {
  id: ID!
  title: String!
  price: Int!
  createdBy: User!
  ownerId: ID!
  agentId: ID
  status: PropertyStatus!
  approvalStatus: ApprovalStatus!
  createdAt: DateTime!
}

enum ApprovalStatus {
  NONE
  PENDING
  APPROVED
  REJECTED
}

enum PropertyStatus { 
  DRAFT
  PUBLISHED
  SOLD
  RENTED
  ARCHIVED
}

extend type User @key(fields: "id") {
  id: ID! @external
}


enum Role {
  ADMIN
  AGENT
  OWNER
  CUSTOMER
}
